### PR TITLE
Parallel SVM training inside each cross validation bin

### PR DESCRIPTION
**Pull request by rengglic**
Introduce parallel training of multiple SVMs inside each cross validation bin.
The threadpool, using posix threads is given in the files threadpool.c and its corresponding header file. The code was written by Mathias Brossard <mathias@brossard.org>.
In order to enable this functionality, the compiler preprocessor flag "_GLIBCXX_PARALLEL" has to be set. The maximum number of concurrent threads per cross validation bin can be set using the execution parameter "ncposthreads". The default value is 1, which will run the training of the SVMs sequentially.

### CODE REVIEW

**Comment by MatthewThe** [comment]
- One of the system tests is failing on Travis, could you find out what's going on there?
- OpenMP parallelization should probably be turned off whenever the threadpool is used, perhaps adding a `!defined(_GLIBCXX_PARALLEL)` to [this line](https://github.com/DS3Lab/percolator/blob/dfd04ba84521318ef2d7e20a6fe1bde714466b20/src/CrossValidation.cpp#L29) would suffice. Alternatively (and probably preferably) we could handle this in the [CommonCMake.txt](https://github.com/DS3Lab/percolator/blob/dfd04ba84521318ef2d7e20a6fe1bde714466b20/CommonCMake.txt#L155), but then the other instances where OpenMP is used should also be replaced by the threadpool. I think the only other place OpenMP is used is for the DOC feature calculation, so it should be easy enough.
- Have you monitored the memory consumption as a function of the number of threads?

**Comment by MatthewThe** [comment]
I just realized I misunderstood how the code works. You are using both OpenMP (3 threads) and threadpool (9 threads per OpenMP thread) at the same time, correct? This will probably work, but wouldn't a pure threadpool solution make more sense?

**Comment by rengglic** [comment]
Hi Matthew. Yes exactly. The nicest way would be to have one threadpool. But it's not that easy without restructuring the entire code. OpenMP would support nested parallel for statements, but only for versions later then 3.1 I think. Also I don't know how it reacts when you have the nested for across multiple functions. Having a single Threadpool with POSIX threads would be a possible option. It's not that easy implementable tough, as with the current code, subsets of the thread's (all the ones in the same cross validation bin) would need to wait for each other after having learned their parameters. There is no proper Threadpool implementation which supports this operation, and I presume implementing one is fairly advanced in other to not introduce racing conditions.
I have fixed the stuff such that the system tests run without any error. I'll commit my code and update / recreate a pull request. Can we run advanced examples to see the speedup running it with 1-9 threads say?

**Comment by MatthewThe** [comment]
Alright, I guess the current OpenMS+threadpool implementation is good enough for the moment then. 

I unfortunately won't have time to run some myself for the next 1.5 week. Do you have some advanced examples to work with? I would suggest to also monitor memory consumption besides the speedup.

**Comment by thabangh** [comment]
Ce has several data sets that he should be able to point Cedric to.

**Comment by MatthewThe** [comment]
This has been reworked into a full OpenMP implementation in #254

**Pull request closed without merging**
